/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast",
  aws_user_pools_id: "ap-southeast-2_CNuOwBmBp",
  aws_user_pools_web_client_id: "3fsrftv9tdphu3sfr6sckv4760",
};

export default awsmobile;
